# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='travels',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_travels', to='travels.Users'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='users',
            field=models.ManyToManyField(related_name='travels', to='travels.Users'),
        ),
    ]
