# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20170627_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travels',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travels',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_travels', to='users.Users'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='users',
            field=models.ManyToManyField(related_name='travels', to='users.Users'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
